BEGIN;

-- ==========================================
-- 1. PRODUCT BATCHES
-- ==========================================
INSERT INTO public.product_batch (id, quantity, expiration_date, product_id) VALUES (1, 25, '2026-04-06', 156);
INSERT INTO public.product_batch (id, quantity, expiration_date, product_id) VALUES (2, 3, '2026-04-06', 272);
INSERT INTO public.product_batch (id, quantity, expiration_date, product_id) VALUES (3, 90, '2026-04-06', 164);
INSERT INTO public.product_batch (id, quantity, expiration_date, product_id) VALUES (4, 43, '2026-03-09', 160);
INSERT INTO public.product_batch (id, quantity, expiration_date, product_id) VALUES (5, 116, '2026-03-10', 167);
INSERT INTO public.product_batch (id, quantity, expiration_date, product_id) VALUES (6, 130, '2026-04-06', 254);
INSERT INTO public.product_batch (id, quantity, expiration_date, product_id) VALUES (7, 132, '2026-04-06', 255);
INSERT INTO public.product_batch (id, quantity, expiration_date, product_id) VALUES (8, 84, '2026-03-13', 169);
INSERT INTO public.product_batch (id, quantity, expiration_date, product_id) VALUES (9, 368, '2026-04-06', 252);
INSERT INTO public.product_batch (id, quantity, expiration_date, product_id) VALUES (10, 455, '2026-04-06', 251);
INSERT INTO public.product_batch (id, quantity, expiration_date, product_id) VALUES (11, 379, '2026-04-06', 253);
INSERT INTO public.product_batch (id, quantity, expiration_date, product_id) VALUES (12, 577, '2026-04-06', 264);
INSERT INTO public.product_batch (id, quantity, expiration_date, product_id) VALUES (13, 835, '2026-04-06', 273);
INSERT INTO public.product_batch (id, quantity, expiration_date, product_id) VALUES (14, 76, '2026-04-06', 161);
INSERT INTO public.product_batch (id, quantity, expiration_date, product_id) VALUES (15, 107, '2026-04-06', 166);
INSERT INTO public.product_batch (id, quantity, expiration_date, product_id) VALUES (16, 63, '2026-04-06', 172);
INSERT INTO public.product_batch (id, quantity, expiration_date, product_id) VALUES (17, 2, '2026-04-06', 261);
INSERT INTO public.product_batch (id, quantity, expiration_date, product_id) VALUES (18, 363, '2026-04-06', 256);
INSERT INTO public.product_batch (id, quantity, expiration_date, product_id) VALUES (19, 1, '2026-04-06', 259);
INSERT INTO public.product_batch (id, quantity, expiration_date, product_id) VALUES (20, 31, '2026-04-06', 171);
INSERT INTO public.product_batch (id, quantity, expiration_date, product_id) VALUES (21, 88, '2026-04-06', 262);
INSERT INTO public.product_batch (id, quantity, expiration_date, product_id) VALUES (22, 339, '2026-04-06', 250);
INSERT INTO public.product_batch (id, quantity, expiration_date, product_id) VALUES (23, 441, '2026-04-06', 268);
INSERT INTO public.product_batch (id, quantity, expiration_date, product_id) VALUES (24, 889, '2026-04-06', 270);
INSERT INTO public.product_batch (id, quantity, expiration_date, product_id) VALUES (25, 790, '2026-04-06', 271);
INSERT INTO public.product_batch (id, quantity, expiration_date, product_id) VALUES (26, 118, '2026-04-06', 175);
INSERT INTO public.product_batch (id, quantity, expiration_date, product_id) VALUES (27, 48, '2026-04-06', 194);
INSERT INTO public.product_batch (id, quantity, expiration_date, product_id) VALUES (28, 81, '2026-04-06', 177);
INSERT INTO public.product_batch (id, quantity, expiration_date, product_id) VALUES (29, 76, '2026-04-06', 178);
INSERT INTO public.product_batch (id, quantity, expiration_date, product_id) VALUES (30, 49, '2026-03-10', 158);
INSERT INTO public.product_batch (id, quantity, expiration_date, product_id) VALUES (31, 221, '2026-04-06', 266);
INSERT INTO public.product_batch (id, quantity, expiration_date, product_id) VALUES (32, 174, '2026-04-06', 269);
INSERT INTO public.product_batch (id, quantity, expiration_date, product_id) VALUES (33, 10, '2026-03-14', 163);
INSERT INTO public.product_batch (id, quantity, expiration_date, product_id) VALUES (34, 35, '2026-04-06', 163);
INSERT INTO public.product_batch (id, quantity, expiration_date, product_id) VALUES (35, 41, '2026-04-06', 176);
INSERT INTO public.product_batch (id, quantity, expiration_date, product_id) VALUES (36, 102, '2026-04-06', 183);
INSERT INTO public.product_batch (id, quantity, expiration_date, product_id) VALUES (37, 101, '2026-04-06', 162);
INSERT INTO public.product_batch (id, quantity, expiration_date, product_id) VALUES (38, 20, '2026-04-06', 281);
INSERT INTO public.product_batch (id, quantity, expiration_date, product_id) VALUES (39, 29, '2026-04-06', 182);
INSERT INTO public.product_batch (id, quantity, expiration_date, product_id) VALUES (40, 98, '2026-04-06', 148);
INSERT INTO public.product_batch (id, quantity, expiration_date, product_id) VALUES (41, 16, '2026-04-06', 149);
INSERT INTO public.product_batch (id, quantity, expiration_date, product_id) VALUES (42, 31, '2026-04-06', 151);
INSERT INTO public.product_batch (id, quantity, expiration_date, product_id) VALUES (43, 109, '2026-03-08', 152);
INSERT INTO public.product_batch (id, quantity, expiration_date, product_id) VALUES (44, 48, '2026-03-11', 153);
INSERT INTO public.product_batch (id, quantity, expiration_date, product_id) VALUES (45, 115, '2026-03-13', 170);
INSERT INTO public.product_batch (id, quantity, expiration_date, product_id) VALUES (46, 55, '2026-04-06', 137);
INSERT INTO public.product_batch (id, quantity, expiration_date, product_id) VALUES (47, 97, '2026-04-06', 191);
INSERT INTO public.product_batch (id, quantity, expiration_date, product_id) VALUES (48, 74, '2026-04-06', 189);
INSERT INTO public.product_batch (id, quantity, expiration_date, product_id) VALUES (49, 38, '2026-04-06', 190);
INSERT INTO public.product_batch (id, quantity, expiration_date, product_id) VALUES (50, 34, '2026-04-06', 143);
INSERT INTO public.product_batch (id, quantity, expiration_date, product_id) VALUES (51, 54, '2026-04-06', 157);
INSERT INTO public.product_batch (id, quantity, expiration_date, product_id) VALUES (52, 112, '2026-04-06', 159);
INSERT INTO public.product_batch (id, quantity, expiration_date, product_id) VALUES (53, 3, '2026-04-06', 139);
INSERT INTO public.product_batch (id, quantity, expiration_date, product_id) VALUES (54, 60, '2026-03-12', 192);
INSERT INTO public.product_batch (id, quantity, expiration_date, product_id) VALUES (55, 61, '2026-03-11', 141);
INSERT INTO public.product_batch (id, quantity, expiration_date, product_id) VALUES (56, 84, '2026-03-12', 147);
INSERT INTO public.product_batch (id, quantity, expiration_date, product_id) VALUES (57, 75, '2026-03-12', 155);
INSERT INTO public.product_batch (id, quantity, expiration_date, product_id) VALUES (58, 82, '2026-06-06', 138);
INSERT INTO public.product_batch (id, quantity, expiration_date, product_id) VALUES (59, 142, '2026-04-06', 138);
INSERT INTO public.product_batch (id, quantity, expiration_date, product_id) VALUES (60, 37, '2026-04-06', 142);
INSERT INTO public.product_batch (id, quantity, expiration_date, product_id) VALUES (61, 104, '2026-04-06', 144);
INSERT INTO public.product_batch (id, quantity, expiration_date, product_id) VALUES (62, 94, '2026-04-06', 224);
INSERT INTO public.product_batch (id, quantity, expiration_date, product_id) VALUES (63, 32, '2026-04-06', 222);
INSERT INTO public.product_batch (id, quantity, expiration_date, product_id) VALUES (64, 64, '2026-04-06', 195);
INSERT INTO public.product_batch (id, quantity, expiration_date, product_id) VALUES (65, 70, '2026-04-06', 205);
INSERT INTO public.product_batch (id, quantity, expiration_date, product_id) VALUES (66, 117, '2026-04-06', 217);
INSERT INTO public.product_batch (id, quantity, expiration_date, product_id) VALUES (67, 114, '2026-04-06', 219);
INSERT INTO public.product_batch (id, quantity, expiration_date, product_id) VALUES (68, 78, '2026-04-06', 220);
INSERT INTO public.product_batch (id, quantity, expiration_date, product_id) VALUES (69, 94, '2026-04-06', 221);
INSERT INTO public.product_batch (id, quantity, expiration_date, product_id) VALUES (70, 10, '2026-04-06', 279);
INSERT INTO public.product_batch (id, quantity, expiration_date, product_id) VALUES (71, 107, '2026-03-06', 223);
INSERT INTO public.product_batch (id, quantity, expiration_date, product_id) VALUES (72, 22, '2026-03-13', 196);
INSERT INTO public.product_batch (id, quantity, expiration_date, product_id) VALUES (73, 92, '2026-04-06', 197);
INSERT INTO public.product_batch (id, quantity, expiration_date, product_id) VALUES (74, 105, '2026-04-06', 225);
INSERT INTO public.product_batch (id, quantity, expiration_date, product_id) VALUES (75, 33, '2026-04-06', 216);

-- ==========================================
-- 2. DISCOUNTS
-- ==========================================
INSERT INTO public.discount (id, discount_end_date, discount_start_date, discount_type, discount_value, product_id) VALUES (5, '2026-12-31 23:59:59.000000 +00:00', '2026-01-01 00:00:00.000000 +00:00', 'PERCENT', 1, 163);

-- ==========================================
-- 3. PRODUCT ATTRIBUTES
-- ==========================================
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (37, 'Calories', '237 kcal', 137);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (38, 'Carbs', '2 g', 137);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (39, 'Proteins', '9 g', 137);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (40, 'Fats', '23 g', 137);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (41, 'Calories', '149 kcal', 138);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (42, 'Carbs', '4 g', 138);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (43, 'Proteins', '17 g', 138);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (44, 'Fats', '24 g', 138);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (45, 'Calories', '126 kcal', 139);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (46, 'Carbs', '13 g', 139);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (47, 'Proteins', '6 g', 139);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (48, 'Fats', '19 g', 139);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (53, 'Calories', '202 kcal', 141);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (54, 'Carbs', '21 g', 141);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (55, 'Proteins', '14 g', 141);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (56, 'Fats', '3 g', 141);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (57, 'Calories', '78 kcal', 142);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (58, 'Carbs', '14 g', 142);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (59, 'Proteins', '14 g', 142);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (60, 'Fats', '6 g', 142);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (61, 'Calories', '78 kcal', 143);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (62, 'Carbs', '43 g', 143);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (63, 'Proteins', '20 g', 143);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (64, 'Fats', '23 g', 143);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (65, 'Calories', '303 kcal', 144);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (66, 'Carbs', '50 g', 144);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (67, 'Proteins', '2 g', 144);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (68, 'Fats', '3 g', 144);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (77, 'Calories', '107 kcal', 147);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (78, 'Carbs', '11 g', 147);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (79, 'Proteins', '20 g', 147);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (80, 'Fats', '20 g', 147);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (81, 'Calories', '345 kcal', 148);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (82, 'Carbs', '29 g', 148);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (83, 'Proteins', '16 g', 148);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (84, 'Fats', '23 g', 148);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (85, 'Calories', '126 kcal', 149);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (86, 'Carbs', '6 g', 149);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (87, 'Proteins', '7 g', 149);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (88, 'Fats', '12 g', 149);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (93, 'Calories', '36 kcal', 151);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (94, 'Carbs', '39 g', 151);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (95, 'Proteins', '7 g', 151);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (96, 'Fats', '24 g', 151);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (97, 'Calories', '63 kcal', 152);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (98, 'Carbs', '27 g', 152);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (99, 'Proteins', '6 g', 152);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (100, 'Fats', '19 g', 152);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (101, 'Calories', '75 kcal', 153);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (102, 'Carbs', '19 g', 153);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (103, 'Proteins', '1 g', 153);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (104, 'Fats', '11 g', 153);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (109, 'Calories', '134 kcal', 155);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (110, 'Carbs', '27 g', 155);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (111, 'Proteins', '19 g', 155);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (112, 'Fats', '3 g', 155);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (113, 'Calories', '219 kcal', 156);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (114, 'Carbs', '26 g', 156);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (115, 'Proteins', '7 g', 156);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (116, 'Fats', '13 g', 156);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (117, 'Calories', '46 kcal', 157);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (118, 'Carbs', '3 g', 157);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (119, 'Proteins', '13 g', 157);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (120, 'Fats', '12 g', 157);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (121, 'Calories', '247 kcal', 158);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (122, 'Carbs', '39 g', 158);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (123, 'Proteins', '13 g', 158);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (124, 'Fats', '13 g', 158);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (125, 'Calories', '235 kcal', 159);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (126, 'Carbs', '18 g', 159);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (127, 'Proteins', '20 g', 159);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (128, 'Fats', '0 g', 159);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (129, 'Calories', '150 kcal', 160);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (130, 'Carbs', '4 g', 160);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (131, 'Proteins', '18 g', 160);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (132, 'Fats', '13 g', 160);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (133, 'Calories', '319 kcal', 161);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (134, 'Carbs', '31 g', 161);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (135, 'Proteins', '16 g', 161);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (136, 'Fats', '19 g', 161);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (137, 'Calories', '189 kcal', 162);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (138, 'Carbs', '19 g', 162);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (139, 'Proteins', '7 g', 162);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (140, 'Fats', '21 g', 162);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (141, 'Calories', '314 kcal', 163);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (142, 'Carbs', '15 g', 163);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (143, 'Proteins', '6 g', 163);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (144, 'Fats', '3 g', 163);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (145, 'Calories', '205 kcal', 164);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (146, 'Carbs', '3 g', 164);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (147, 'Proteins', '20 g', 164);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (148, 'Fats', '5 g', 164);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (149, 'Calories', '317 kcal', 165);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (150, 'Carbs', '41 g', 165);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (151, 'Proteins', '7 g', 165);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (152, 'Fats', '24 g', 165);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (153, 'Calories', '57 kcal', 166);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (154, 'Carbs', '12 g', 166);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (155, 'Proteins', '18 g', 166);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (156, 'Fats', '13 g', 166);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (157, 'Calories', '28 kcal', 167);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (158, 'Carbs', '7 g', 167);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (159, 'Proteins', '14 g', 167);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (160, 'Fats', '1 g', 167);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (165, 'Calories', '153 kcal', 169);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (166, 'Carbs', '3 g', 169);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (167, 'Proteins', '10 g', 169);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (168, 'Fats', '16 g', 169);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (169, 'Calories', '275 kcal', 170);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (170, 'Carbs', '38 g', 170);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (171, 'Proteins', '20 g', 170);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (172, 'Fats', '0 g', 170);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (173, 'Calories', '360 kcal', 171);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (174, 'Carbs', '38 g', 171);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (175, 'Proteins', '17 g', 171);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (176, 'Fats', '1 g', 171);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (177, 'Calories', '72 kcal', 172);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (178, 'Carbs', '20 g', 172);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (179, 'Proteins', '9 g', 172);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (180, 'Fats', '9 g', 172);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (181, 'Calories', '344 kcal', 173);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (182, 'Carbs', '45 g', 173);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (183, 'Proteins', '10 g', 173);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (184, 'Fats', '3 g', 173);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (189, 'Calories', '326 kcal', 175);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (190, 'Carbs', '40 g', 175);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (191, 'Proteins', '10 g', 175);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (192, 'Fats', '14 g', 175);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (193, 'Calories', '196 kcal', 176);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (194, 'Carbs', '24 g', 176);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (195, 'Proteins', '17 g', 176);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (196, 'Fats', '17 g', 176);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (197, 'Calories', '86 kcal', 177);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (198, 'Carbs', '29 g', 177);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (199, 'Proteins', '14 g', 177);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (200, 'Fats', '19 g', 177);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (201, 'Calories', '226 kcal', 178);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (202, 'Carbs', '35 g', 178);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (203, 'Proteins', '10 g', 178);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (204, 'Fats', '24 g', 178);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (209, 'Calories', '336 kcal', 180);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (210, 'Carbs', '24 g', 180);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (211, 'Proteins', '6 g', 180);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (212, 'Fats', '11 g', 180);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (213, 'Calories', '321 kcal', 181);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (214, 'Carbs', '42 g', 181);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (215, 'Proteins', '9 g', 181);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (216, 'Fats', '4 g', 181);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (217, 'Calories', '129 kcal', 182);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (218, 'Carbs', '46 g', 182);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (219, 'Proteins', '14 g', 182);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (220, 'Fats', '18 g', 182);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (221, 'Calories', '96 kcal', 183);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (222, 'Carbs', '49 g', 183);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (223, 'Proteins', '4 g', 183);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (224, 'Fats', '20 g', 183);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (237, 'Calories', '129 kcal', 187);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (238, 'Carbs', '2 g', 187);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (239, 'Proteins', '1 g', 187);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (240, 'Fats', '18 g', 187);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (241, 'Calories', '125 kcal', 188);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (242, 'Carbs', '9 g', 188);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (243, 'Proteins', '10 g', 188);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (244, 'Fats', '4 g', 188);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (245, 'Calories', '264 kcal', 189);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (246, 'Carbs', '27 g', 189);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (247, 'Proteins', '17 g', 189);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (248, 'Fats', '22 g', 189);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (249, 'Calories', '87 kcal', 190);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (250, 'Carbs', '39 g', 190);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (251, 'Proteins', '15 g', 190);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (252, 'Fats', '2 g', 190);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (253, 'Calories', '267 kcal', 191);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (254, 'Carbs', '50 g', 191);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (255, 'Proteins', '13 g', 191);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (256, 'Fats', '16 g', 191);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (257, 'Calories', '198 kcal', 192);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (258, 'Carbs', '22 g', 192);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (259, 'Proteins', '20 g', 192);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (260, 'Fats', '11 g', 192);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (265, 'Calories', '86 kcal', 194);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (266, 'Carbs', '46 g', 194);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (267, 'Proteins', '17 g', 194);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (268, 'Fats', '22 g', 194);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (269, 'Calories', '208 kcal', 195);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (270, 'Carbs', '22 g', 195);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (271, 'Proteins', '12 g', 195);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (272, 'Fats', '17 g', 195);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (273, 'Calories', '263 kcal', 196);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (274, 'Carbs', '37 g', 196);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (275, 'Proteins', '17 g', 196);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (276, 'Fats', '4 g', 196);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (277, 'Calories', '37 kcal', 197);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (278, 'Carbs', '2 g', 197);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (279, 'Proteins', '1 g', 197);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (280, 'Fats', '8 g', 197);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (309, 'Calories', '314 kcal', 205);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (310, 'Carbs', '22 g', 205);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (311, 'Proteins', '6 g', 205);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (312, 'Fats', '3 g', 205);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (353, 'Calories', '48 kcal', 216);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (354, 'Carbs', '25 g', 216);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (355, 'Proteins', '6 g', 216);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (356, 'Fats', '12 g', 216);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (357, 'Calories', '180 kcal', 217);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (358, 'Carbs', '38 g', 217);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (359, 'Proteins', '4 g', 217);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (360, 'Fats', '22 g', 217);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (365, 'Calories', '367 kcal', 219);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (366, 'Carbs', '46 g', 219);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (367, 'Proteins', '2 g', 219);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (368, 'Fats', '5 g', 219);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (369, 'Calories', '135 kcal', 220);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (370, 'Carbs', '22 g', 220);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (371, 'Proteins', '11 g', 220);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (372, 'Fats', '11 g', 220);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (373, 'Calories', '21 kcal', 221);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (374, 'Carbs', '16 g', 221);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (375, 'Proteins', '7 g', 221);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (376, 'Fats', '13 g', 221);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (377, 'Calories', '41 kcal', 222);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (378, 'Carbs', '51 g', 222);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (379, 'Proteins', '9 g', 222);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (380, 'Fats', '22 g', 222);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (381, 'Calories', '49 kcal', 223);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (382, 'Carbs', '17 g', 223);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (383, 'Proteins', '13 g', 223);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (384, 'Fats', '0 g', 223);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (385, 'Calories', '303 kcal', 224);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (386, 'Carbs', '11 g', 224);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (387, 'Proteins', '19 g', 224);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (388, 'Fats', '13 g', 224);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (389, 'Calories', '132 kcal', 225);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (390, 'Carbs', '10 g', 225);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (391, 'Proteins', '12 g', 225);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (392, 'Fats', '7 g', 225);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (489, 'Calories', '19 kcal', 250);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (490, 'Carbs', '16 g', 250);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (491, 'Proteins', '0 g', 250);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (492, 'Fats', '0 g', 250);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (493, 'Calories', '50 kcal', 251);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (494, 'Carbs', '4 g', 251);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (495, 'Proteins', '0 g', 251);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (496, 'Fats', '0 g', 251);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (497, 'Calories', '26 kcal', 252);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (498, 'Carbs', '9 g', 252);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (499, 'Proteins', '1 g', 252);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (500, 'Fats', '0 g', 252);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (501, 'Calories', '45 kcal', 253);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (502, 'Carbs', '12 g', 253);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (503, 'Proteins', '2 g', 253);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (504, 'Fats', '0 g', 253);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (505, 'Calories', '37 kcal', 254);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (506, 'Carbs', '3 g', 254);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (507, 'Proteins', '0 g', 254);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (508, 'Fats', '0 g', 254);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (509, 'Calories', '43 kcal', 255);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (510, 'Carbs', '2 g', 255);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (511, 'Proteins', '1 g', 255);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (512, 'Fats', '0 g', 255);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (513, 'Calories', '64 kcal', 256);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (514, 'Carbs', '15 g', 256);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (515, 'Proteins', '1 g', 256);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (516, 'Fats', '0 g', 256);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (517, 'Calories', '29 kcal', 257);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (518, 'Carbs', '5 g', 257);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (519, 'Proteins', '1 g', 257);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (520, 'Fats', '0 g', 257);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (521, 'Calories', '13 kcal', 258);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (522, 'Carbs', '6 g', 258);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (523, 'Proteins', '1 g', 258);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (524, 'Fats', '0 g', 258);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (525, 'Calories', '14 kcal', 259);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (526, 'Carbs', '3 g', 259);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (527, 'Proteins', '0 g', 259);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (528, 'Fats', '0 g', 259);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (533, 'Calories', '55 kcal', 261);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (534, 'Carbs', '11 g', 261);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (535, 'Proteins', '2 g', 261);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (536, 'Fats', '0 g', 261);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (537, 'Calories', '29 kcal', 262);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (538, 'Carbs', '2 g', 262);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (539, 'Proteins', '0 g', 262);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (540, 'Fats', '0 g', 262);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (541, 'Calories', '54 kcal', 263);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (542, 'Carbs', '4 g', 263);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (543, 'Proteins', '1 g', 263);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (544, 'Fats', '0 g', 263);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (545, 'Calories', '24 kcal', 264);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (546, 'Carbs', '4 g', 264);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (547, 'Proteins', '1 g', 264);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (548, 'Fats', '0 g', 264);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (549, 'Calories', '52 kcal', 265);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (550, 'Carbs', '12 g', 265);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (551, 'Proteins', '1 g', 265);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (552, 'Fats', '0 g', 265);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (553, 'Calories', '37 kcal', 266);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (554, 'Carbs', '10 g', 266);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (555, 'Proteins', '2 g', 266);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (556, 'Fats', '0 g', 266);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (557, 'Calories', '49 kcal', 267);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (558, 'Carbs', '16 g', 267);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (559, 'Proteins', '1 g', 267);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (560, 'Fats', '0 g', 267);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (561, 'Calories', '25 kcal', 268);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (562, 'Carbs', '9 g', 268);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (563, 'Proteins', '0 g', 268);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (564, 'Fats', '0 g', 268);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (565, 'Calories', '22 kcal', 269);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (566, 'Carbs', '4 g', 269);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (567, 'Proteins', '0 g', 269);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (568, 'Fats', '0 g', 269);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (569, 'Calories', '40 kcal', 270);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (570, 'Carbs', '9 g', 270);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (571, 'Proteins', '2 g', 270);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (572, 'Fats', '0 g', 270);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (573, 'Calories', '18 kcal', 271);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (574, 'Carbs', '3 g', 271);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (575, 'Proteins', '0 g', 271);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (576, 'Fats', '0 g', 271);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (577, 'Calories', '21 kcal', 272);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (578, 'Carbs', '2 g', 272);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (579, 'Proteins', '2 g', 272);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (580, 'Fats', '0 g', 272);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (581, 'Calories', '46 kcal', 273);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (582, 'Carbs', '7 g', 273);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (583, 'Proteins', '0 g', 273);
INSERT INTO public.product_attribute (id, name, value, product_id) VALUES (584, 'Fats', '0 g', 273);
INSERT INTO public.product_attribute (name, value, product_id) VALUES
('Carbs', '0 g', 282), ('Fats', '3.6 g', 282),
('Carbs', '0 g', 283), ('Fats', '10.9 g', 283),
('Carbs', '0 g', 284), ('Fats', '8.1 g', 284),
('Carbs', '0 g', 285), ('Fats', '20 g', 285),
('Carbs', '0 g', 286), ('Fats', '17 g', 286),
('Carbs', '0 g', 287), ('Fats', '10 g', 287),
('Carbs', '0 g', 288), ('Fats', '22 g', 288),
('Carbs', '0 g', 289), ('Fats', '13 g', 289),
('Carbs', '0 g', 290), ('Fats', '6 g', 290),
('Carbs', '0 g', 291), ('Fats', '5 g', 291),
('Carbs', '3 g', 292), ('Fats', '1.5 g', 292),
('Carbs', '2 g', 294), ('Fats', '18 g', 294),
('Carbs', '1 g', 295), ('Fats', '4 g', 295);
INSERT INTO public.product_image (id, image_url, product_id) VALUES (37, '/products/local-farmers-banane-100g.jpg', 250);
INSERT INTO public.product_image (id, image_url, product_id) VALUES (38, '/products/local-farmers-mere-ionatan-100g.jpg', 251);
INSERT INTO public.product_image (id, image_url, product_id) VALUES (39, '/products/local-farmers-mere-granny-smith-100g.jpg', 252);
INSERT INTO public.product_image (id, image_url, product_id) VALUES (40, '/products/local-farmers-pere-100g.jpg', 253);
INSERT INTO public.product_image (id, image_url, product_id) VALUES (41, '/products/local-farmers-prune-100g.jpg', 254);
INSERT INTO public.product_image (id, image_url, product_id) VALUES (42, '/products/local-farmers-cirese-100g.jpg', 255);
INSERT INTO public.product_image (id, image_url, product_id) VALUES (43, '/products/local-farmers-capsuni-100g.jpg', 256);
INSERT INTO public.product_image (id, image_url, product_id) VALUES (44, '/products/local-farmers-rosii-100g.jpg', 257);
INSERT INTO public.product_image (id, image_url, product_id) VALUES (45, '/products/local-farmers-rosii-cherry-100g.jpg', 258);
INSERT INTO public.product_image (id, image_url, product_id) VALUES (46, '/products/local-farmers-castraveti-100g.jpg', 259);
INSERT INTO public.product_image (id, image_url, product_id) VALUES (48, '/products/local-farmers-ceapa-galbena-100g.jpg', 261);
INSERT INTO public.product_image (id, image_url, product_id) VALUES (49, '/products/local-farmers-ceapa-rosie-100g.jpg', 262);
INSERT INTO public.product_image (id, image_url, product_id) VALUES (50, '/products/local-farmers-morcovi-100g.jpg', 263);
INSERT INTO public.product_image (id, image_url, product_id) VALUES (51, '/products/local-farmers-cartofi-albi-100g.jpg', 264);
INSERT INTO public.product_image (id, image_url, product_id) VALUES (52, '/products/local-farmers-cartofi-rosii-100g.jpg', 265);
INSERT INTO public.product_image (id, image_url, product_id) VALUES (53, '/products/local-farmers-usturoi-100g.jpg', 266);
INSERT INTO public.product_image (id, image_url, product_id) VALUES (54, '/products/local-farmers-varza-alba-100g.jpg', 267);
INSERT INTO public.product_image (id, image_url, product_id) VALUES (55, '/products/local-farmers-salata-verde-100g.jpg', 268);
INSERT INTO public.product_image (id, image_url, product_id) VALUES (56, '/products/local-farmers-fructe-de-padure-100g.jpg', 269);
INSERT INTO public.product_image (id, image_url, product_id) VALUES (57, '/products/local-farmers-piersici-100g.jpg', 270);
INSERT INTO public.product_image (id, image_url, product_id) VALUES (58, '/products/local-farmers-pepene-100g.jpg', 271);
INSERT INTO public.product_image (id, image_url, product_id) VALUES (59, '/products/local-farmers-zmeura-100g.jpg', 272);
INSERT INTO public.product_image (id, image_url, product_id) VALUES (60, '/products/local-farmers-struguri-100g.jpg', 273);
INSERT INTO public.product_image (id, image_url, product_id) VALUES (61, '/products/coca-cola-coca-cola-original-2l.jpg', 137);
INSERT INTO public.product_image (id, image_url, product_id) VALUES (62, '/products/coca-cola-coca-cola-zero-2l.jpg', 138);
INSERT INTO public.product_image (id, image_url, product_id) VALUES (63, '/products/coca-cola-fanta-portocale-2l.jpg', 139);
INSERT INTO public.product_image (id, image_url, product_id) VALUES (64, '/products/pepsi-pepsi-cola-2l.jpg', 141);
INSERT INTO public.product_image (id, image_url, product_id) VALUES (65, '/products/pepsi-pepsi-max-2l.jpg', 142);
INSERT INTO public.product_image (id, image_url, product_id) VALUES (66, '/products/pepsi-mirinda-2l.jpg', 143);
INSERT INTO public.product_image (id, image_url, product_id) VALUES (67, '/products/dorna-apa-minerala-15l.jpg', 144);
INSERT INTO public.product_image (id, image_url, product_id) VALUES (68, '/products/borsec-apa-plata-2l.jpg', 147);
INSERT INTO public.product_image (id, image_url, product_id) VALUES (69, '/products/bucovina-apa-plata-15l.jpg', 148);
INSERT INTO public.product_image (id, image_url, product_id) VALUES (70, '/products/bucovina-apa-minerala-15l.jpg', 149);
INSERT INTO public.product_image (id, image_url, product_id) VALUES (71, '/products/aqua-carpatica-apa-minerala-15l.jpg', 151);
INSERT INTO public.product_image (id, image_url, product_id) VALUES (72, '/products/lipton-ice-tea-piersica-15l.jpg', 152);
INSERT INTO public.product_image (id, image_url, product_id) VALUES (73, '/products/lipton-ice-tea-lamaie-15l.jpg', 153);
INSERT INTO public.product_image (id, image_url, product_id) VALUES (74, '/products/lays-chipsuri-cu-sare-140g.jpg', 155);
INSERT INTO public.product_image (id, image_url, product_id) VALUES (75, '/products/lays-chipsuri-paprika-140g.jpg', 156);
INSERT INTO public.product_image (id, image_url, product_id) VALUES (76, '/products/lays-chipsuri-cascaval-140g.jpg', 157);
INSERT INTO public.product_image (id, image_url, product_id) VALUES (77, '/products/pringles-chipsuri-original-165g.jpg', 158);
INSERT INTO public.product_image (id, image_url, product_id) VALUES (78, '/products/pringles-chipsuri-sour-cream-and-onion-165g.jpg', 159);
INSERT INTO public.product_image (id, image_url, product_id) VALUES (79, '/products/chio-chipsuri-cu-sare-140g.jpg', 160);
INSERT INTO public.product_image (id, image_url, product_id) VALUES (80, '/products/chio-chipsuri-smantana-140g.jpg', 161);
INSERT INTO public.product_image (id, image_url, product_id) VALUES (81, '/products/7days-croissant-cacao-80g.jpg', 162);
INSERT INTO public.product_image (id, image_url, product_id) VALUES (82, '/products/7days-croissant-vanilie-80g.jpg', 163);
INSERT INTO public.product_image (id, image_url, product_id) VALUES (83, '/products/bake-rolls-bake-rolls-usturoi-80g.jpg', 164);
INSERT INTO public.product_image (id, image_url, product_id) VALUES (84, '/products/milka-ciocolata-cu-lapte-100g.jpg', 165);
INSERT INTO public.product_image (id, image_url, product_id) VALUES (85, '/products/milka-ciocolata-cu-alune-100g.jpg', 166);
INSERT INTO public.product_image (id, image_url, product_id) VALUES (86, '/products/milka-ciocolata-oreo-100g.jpg', 167);
INSERT INTO public.product_image (id, image_url, product_id) VALUES (87, '/products/kinder-ciocolata-100g.jpg', 169);
INSERT INTO public.product_image (id, image_url, product_id) VALUES (88, '/products/kinder-surprise-20g.jpg', 170);
INSERT INTO public.product_image (id, image_url, product_id) VALUES (89, '/products/nutella-crema-de-alune-400g.jpg', 171);
INSERT INTO public.product_image (id, image_url, product_id) VALUES (90, '/products/nutella-b-ready-132g.jpg', 172);
INSERT INTO public.product_image (id, image_url, product_id) VALUES (91, '/products/mars-baton-ciocolata-50g.jpg', 173);
INSERT INTO public.product_image (id, image_url, product_id) VALUES (92, '/products/oreo-biscuiti-original-154g.jpg', 175);
INSERT INTO public.product_image (id, image_url, product_id) VALUES (93, '/products/oreo-biscuiti-double-creme-157g.jpg', 176);
INSERT INTO public.product_image (id, image_url, product_id) VALUES (94, '/products/napolact-lapte-15-1l.jpg', 177);
INSERT INTO public.product_image (id, image_url, product_id) VALUES (95, '/products/napolact-lapte-35-1l.jpg', 178);
INSERT INTO public.product_image (id, image_url, product_id) VALUES (97, '/products/zuzu-lapte-15-1l.jpg', 181);
INSERT INTO public.product_image (id, image_url, product_id) VALUES (98, '/products/zuzu-iaurt-natur-140g.jpg', 182);
INSERT INTO public.product_image (id, image_url, product_id) VALUES (99, '/products/danone-activia-natur-140g.jpg', 183);
INSERT INTO public.product_image (id, image_url, product_id) VALUES (100, '/products/president-unt-82-200g.jpg', 187);
INSERT INTO public.product_image (id, image_url, product_id) VALUES (101, '/products/president-camembert-250g.jpg', 188);
INSERT INTO public.product_image (id, image_url, product_id) VALUES (102, '/products/barilla-penne-rigate-500g.jpg', 189);
INSERT INTO public.product_image (id, image_url, product_id) VALUES (103, '/products/barilla-spaghetti-500g.jpg', 190);
INSERT INTO public.product_image (id, image_url, product_id) VALUES (104, '/products/barilla-fusilli-500g.jpg', 191);
INSERT INTO public.product_image (id, image_url, product_id) VALUES (105, '/products/baneasa-faina-alba-000-1kg.jpg', 192);
INSERT INTO public.product_image (id, image_url, product_id) VALUES (106, '/products/heinz-ketchup-dulce-400g.jpg', 194);
INSERT INTO public.product_image (id, image_url, product_id) VALUES (107, '/products/heinz-ketchup-picant-400g.jpg', 195);
INSERT INTO public.product_image (id, image_url, product_id) VALUES (108, '/products/hellmanns-maioneza-original-400ml.jpg', 196);
INSERT INTO public.product_image (id, image_url, product_id) VALUES (109, '/products/mutti-pulpa-de-rosii-400g.jpg', 197);
INSERT INTO public.product_image (id, image_url, product_id) VALUES (115, '/products/local-farmers-rosii-cherry-250g.jpg', 205);
INSERT INTO public.product_image (id, image_url, product_id) VALUES (125, '/products/local-farmers-oua-proaspete-m-10buc.jpg', 216);
INSERT INTO public.product_image (id, image_url, product_id) VALUES (126, '/products/local-farmers-oua-proaspete-l-30buc.jpg', 217);
INSERT INTO public.product_image (id, image_url, product_id) VALUES (127, '/products/local-farmers-branza-de-burduf-300g.jpg', 219);
INSERT INTO public.product_image (id, image_url, product_id) VALUES (128, '/products/local-farmers-cascaval-de-casa-300g.jpg', 220);
INSERT INTO public.product_image (id, image_url, product_id) VALUES (129, '/products/local-farmers-telemea-de-oaie-400g.jpg', 221);
INSERT INTO public.product_image (id, image_url, product_id) VALUES (130, '/products/local-farmers-miere-poliflora-500g.jpg', 222);
INSERT INTO public.product_image (id, image_url, product_id) VALUES (131, '/products/local-farmers-miere-salcam-500g.jpg', 223);
INSERT INTO public.product_image (id, image_url, product_id) VALUES (132, '/products/local-farmers-paine-de-casa-cu-maia-500g.jpg', 224);
INSERT INTO public.product_image (id, image_url, product_id) VALUES (133, '/products/local-farmers-cozonac-cu-nuca-500g.jpg', 225);
INSERT INTO public.product_image (id, image_url, product_id) VALUES (96, '/products/napolact-telemea-vaca-350g.jpg', 180);

SELECT setval(pg_get_serial_sequence('public.category', 'id'), coalesce(max(id), 1), max(id) IS NOT null) FROM public.category;
SELECT setval(pg_get_serial_sequence('public.brand', 'id'), coalesce(max(id), 1), max(id) IS NOT null) FROM public.brand;
SELECT setval(pg_get_serial_sequence('public.users', 'id'), coalesce(max(id), 1), max(id) IS NOT null) FROM public.users;
SELECT setval(pg_get_serial_sequence('public.address', 'id'), coalesce(max(id), 1), max(id) IS NOT null) FROM public.address;
SELECT setval(pg_get_serial_sequence('public.cart', 'id'), coalesce(max(id), 1), max(id) IS NOT null) FROM public.cart;
SELECT setval(pg_get_serial_sequence('public.product_batch', 'id'), coalesce(max(id), 1), max(id) IS NOT null) FROM public.product_batch;
SELECT setval(pg_get_serial_sequence('public.discount', 'id'), coalesce(max(id), 1), max(id) IS NOT null) FROM public.discount;
SELECT setval(pg_get_serial_sequence('public.product_attribute', 'id'), coalesce(max(id), 1), max(id) IS NOT null) FROM public.product_attribute;
SELECT setval(pg_get_serial_sequence('public.product_image', 'id'), coalesce(max(id), 1), max(id) IS NOT null) FROM public.product_image;

INSERT INTO public.product_image (id, image_url, product_id) VALUES
(134, '/products/local-farmers-piept-de-pui-500g.jpg', 282),
(135, '/products/local-farmers-pulpe-de-pui-500g.jpg', 283),
(136, '/products/local-farmers-aripioare-de-pui-500g.jpg', 284),
(137, '/products/local-farmers-carne-tocata-mixta-500g.jpg', 285),
(138, '/products/local-farmers-ceafa-de-porc-500g.jpg', 286),
(139, '/products/local-farmers-cotlet-de-porc-500g.jpg', 287),
(140, '/products/local-farmers-antricot-de-vita-300g.jpg', 288),
(141, '/products/local-farmers-file-de-somon-250g.jpg', 289),
(142, '/products/local-farmers-pastrav-eviscerat-400g.jpg', 290),
(143, '/products/local-farmers-crap-eviscerat-500g.jpg', 291),
(144, '/products/local-farmers-fructe-de-mare-mix-400g.jpg', 292),
(146, '/products/local-farmers-crenvursti-de-pui-300g.jpg', 294),
(147, '/products/local-farmers-muschi-file-200g.jpg', 295);

COMMIT;
